### PR TITLE
Add CI step to drone

### PR DESCRIPTION
**Pull request by Abban**
This moves our content tests to Drone and adds a new
test to make sure the message files are valid json.

Ticket: https://phabricator.wikimedia.org/T254880

### CODE REVIEW

**Comment by moiikana** [comment]
I assume these changes belongs to this ticket https://phabricator.wikimedia.org/T254880

**Comment by Abban** [comment]
Yep, whoops forgot to add the details when I hit ready for review.

**Review by moiikana — CHANGES_REQUESTED** [review]
Drone isn't passing for this branch yet, I also couldn't figure out yet how to visually integrate Drone to this repository

**Comment by Abban** [comment]
Should be running now

**Review by moiikana — APPROVED** [review]

**Comment by moiikana** [comment]
as far as I understand, for building with composer, drone will download and install those composer dependencies for every change now.
should we also use caching here, like in the other repositories that use drone?

**Pull request merged**
